# 指定语言环境
language: node_js
# 指定需要sudo权限
sudo: required
# 指定node_js版本
node_js: 
  - 7.9.0
# 指定缓存模块，可选。缓存可加快编译速度。
cache:
  directories:
    - node_modules

# 指定博客源码分支，因人而异。hexo博客源码托管在独立repo则不用设置此项
branches:
  only:
    - hexo 

before_install:
  - npm install -g hexo-cli

# Start: Build Lifecycle
install:
  - npm install
  - npm install hexo-deployer-git --save

# 执行清缓存，生成网页操作
script:
  - hexo clean
  - hexo generate

# 设置git提交名，邮箱；替换真实token到_config.yml文件，最后depoy部署
after_script:
  - git config user.name "Gill Chan"
  - git config user.email "jiahao0408@gmail.com"
  # 替换同目录下的_config.yml文件中gh_token字符串为travis后台刚才配置的变量，注意此处sed命令用了双引号。单引号无效！
  - sed -i "s/gh_token/${GH_TOKEN}/g" ./_config.yml
  - hexo deploy

env:
  global:
    secure: RNxBjkgXVW98hPx7CTH08J0ssseMZHU1pBN3sN0tk6cZNJIGqCqAz6Kr8ryVdiKlPjh1JLK/CtjRgYJC+cag+2SH8C+7E+QRURJfwETLzoCyStjDyLGHtZ4vHTtDQdfoJmfoOEVsL7MTWztWIfim9isLwEDRAGHC3Deps0M32I04anz/ks8umhPDgUBmDCoTrYQKI2utdVodXGaZ9zCdxEkdqvlnodkepqdvwmMYFs24i8H+Qrpg7ccvkcYq/x+C6LeXPRcT+6C+Rb2TsIuJ96LJu/LApEKMqxRMvGMkADCEG7/g7xbwcu0bEzFTeWzyEbW+uo7bDturaGGI8d4zQ3FAdki0R39Th/oRJfMQXuDSonocIluhrNHPIum+7An5NtyMo5rxhXHXR2HwOWQsbRepX0hVsdrjc6z1Jbswb/PeKKTwVUQ9Ty5ZeGTv3moxZJ3tS0bpzS8VVEmrrtLajfIl/JQiF6QResglgm8+wjIUnkfQ/1cP4Qe+oraJj5Z4yZaxRv00NQEMUUG5XZKILGeR+98kRhrqvQSzoJaEn/uWXEBVkoVxHQ8+eSlFSPKGgGQPZUAa4P8J/0BdUmo02yR3REapxTpq9IahA9gazPOPt3VUIGPMl8Oc33/MU6ilvsH0Gatn0pcpdtflzEZ1LXtOvUKLXR+n99Z716HfiVI=
