language: node_js
sudo: required
node_js:
- 8.2.1
cache:
  directories:
  - node_modules
notifications: 
email:
  recipients:
  - jiahao0408@gmail.com
  on_success: change
  on_failure: always
branches:
  only:
  - hexo
before_install:
- export TZ='Asia/Shanghai'
- npm install hexo-cli -g
- chmod +x ./commit-message.sh
install:
- npm install
- npm install hexo-deployer-git --save
script:
- hexo clean
- hexo generate
after_script:
- "./commit-message.sh"

env:
  global:
    secure: RNxBjkgXVW98hPx7CTH08J0ssseMZHU1pBN3sN0tk6cZNJIGqCqAz6Kr8ryVdiKlPjh1JLK/CtjRgYJC+cag+2SH8C+7E+QRURJfwETLzoCyStjDyLGHtZ4vHTtDQdfoJmfoOEVsL7MTWztWIfim9isLwEDRAGHC3Deps0M32I04anz/ks8umhPDgUBmDCoTrYQKI2utdVodXGaZ9zCdxEkdqvlnodkepqdvwmMYFs24i8H+Qrpg7ccvkcYq/x+C6LeXPRcT+6C+Rb2TsIuJ96LJu/LApEKMqxRMvGMkADCEG7/g7xbwcu0bEzFTeWzyEbW+uo7bDturaGGI8d4zQ3FAdki0R39Th/oRJfMQXuDSonocIluhrNHPIum+7An5NtyMo5rxhXHXR2HwOWQsbRepX0hVsdrjc6z1Jbswb/PeKKTwVUQ9Ty5ZeGTv3moxZJ3tS0bpzS8VVEmrrtLajfIl/JQiF6QResglgm8+wjIUnkfQ/1cP4Qe+oraJj5Z4yZaxRv00NQEMUUG5XZKILGeR+98kRhrqvQSzoJaEn/uWXEBVkoVxHQ8+eSlFSPKGgGQPZUAa4P8J/0BdUmo02yR3REapxTpq9IahA9gazPOPt3VUIGPMl8Oc33/MU6ilvsH0Gatn0pcpdtflzEZ1LXtOvUKLXR+n99Z716HfiVI=
